### ISSUE TITLE
Stand Alone in AP Mode

### ISSUE THREAD

**Issue by alaintanguay** [tzapu/WiFiManager#121]
Hello

The have any way to use WIFImanager to setup AP mode only ? 

on my application , i can use the ESP on AP mode for direct use cell phone , or setup on home network with wifi manager ?

Now on AP mode my application not run ?

Thanks

Alain

**Comment by tzapu** [comment]
well, currently it is not made to work with AP mode as it forces STA mode when done configuring.
as a short fix, depnding on how you want it running, you might have some toggle variable that doesn t run wifiManager at all, it s really not usefull when you want to run AP mode because it s sole pourpose is to get your device to connect to another AP
