### ISSUE TITLE
public and private methods

### ISSUE THREAD

**Issue by domonetic** [tzapu/WiFiManager#22]
I am reviewing the code to help with the wiki and find something I do not understand.
begin () is called by AutoConnect () but is declared public and I think it should be private.

**Comment by tzapu** [comment]
yes, you are correct again, leftovers from a past version. 
it allwed me then to have an oled connected and do all the steps in the app rather than the library so i can display updates on the screen.
no longer possible, code cleanup is on the table, together with the new callabacks

so nice to see so many people taking interest, thanks

**Comment by domonetic** [comment]
These have no implementation. It is a virtual method? if I remove works just

**String beginConfigMode(void);
void startWebConfig();
String  beginConfigMode(void);
int serverLoop();**
is used internally, it should not be publicly exposed
**String urldecode(const char*);**

**Comment by tzapu** [comment]
hi, did some cleanup as you indicated.]

urldecode i m gonna leave public, as an utilitarian function for others making url requests

**Comment by domonetic** [comment]
Well, I'm helping with the wiki. I hope it will help.

**Comment by tzapu** [comment]
thank you very much, just seen it, so nice to have

**Comment by tzapu** [comment]
there s so much changed, thining at some point the whole things needs another cleanup, then wiki remade
in the mean time, i ll close this
