### ISSUE TITLE
Using library within class

### ISSUE THREAD

**Issue by vman26** [tzapu/WiFiManager#230]
Hi,

I'm trying to use the library within a class,

The problem is I can't use the setAPCallback witin my class:
no matching function for call to 'WiFiManager::setAPCallback(<unresolved overloaded function type>)'

I use:
wifiManager.setAPCallback(configModeCallback);

I have a class named:
`WifiControl`

this is the decleration in the header:
`void configModeCallback (WiFiManager *myWiFiManager);`

and the cpp:

```
void WifiControl::configModeCallback (WiFiManager *myWiFiManager) {
  Serial.println("Entered config mode");
  Serial.println(WiFi.softAPIP());
  //if you used auto generated SSID, print it
  Serial.println(myWiFiManager->getConfigPortalSSID());
  //entered config mode, make led toggle faster
  ticker.attach(0.2, tick);
}
```

I can't figure out how to fix it, any help out there?

**Comment by kluzzebass** [comment]
Because of the way the callbacks are designed in WiFiManager, it's not possible to use class functions (static or otherwise) as callback functions; they simply have to be globally declared functions.

In most cases the required functionality could be solved by simply using boolean flags in the WiFiManager class instead of being clever and using callbacks.

The consequence is that the WiFiManager class cannot readily be used inside another class if you plan on using the callbacks.
