### ISSUE TITLE
An answer about setAPCallback 

### ISSUE THREAD

**Issue by Slartitorto** [tzapu/WiFiManager#231]
Does  setAPCallback  work before startConfigPortal ? Does it work only with autoConnect ?

**Comment by kentaylor** [comment]
See https://github.com/tzapu/WiFiManager/blob/60c22d672fadfdcf139853f766d1824730944e13/examples/AutoConnectWithFeedback/AutoConnectWithFeedback.ino#L25 . I think it would only be useful with autoconnect.

Autoconnect is not great for a non development system because every time the WiFi fails you get a configuration portal and usually you want to wait until the WiFi comes back.
