### ISSUE TITLE
ap scan speed

### ISSUE THREAD

**Issue by tablatronix** [tzapu/WiFiManager#24]
I am at a location where I have maybe 25 AP in range with the same name.

Sometimes the list dumps out immediately, and the page pops up.
Sometimes each one ticks by 1 every 10 seconds, and it takes forever, and the page times out.

I know i can skip scans, but why do you think this is? Maybe i can fix it since I can reproduce easily.

**Comment by tablatronix** [comment]
I didn't realize there was a `yield` in there, maybe its something in my code.

**Comment by tzapu** [comment]
you may wanna try with delay(0) in the library instead of yield... there s been some discussions i ve seen some time ago that it improved things in some library ...

if you see them loading slowly on your screen, it i think it means the data is being sent very slowly. are you far from the esp? Does your firmware have some other loops/timers in parallel ?

cheers

**Comment by tablatronix** [comment]
Im sure its another delay blocking. I have a button library scanning for button presses I recently added.
Works fast when I commented out the yield.

( hehe, I think the scheduler library still says beta.)

**Comment by tzapu** [comment]
does it work any better with delay(0) instead of the yield()?

**Comment by tablatronix** [comment]
It sees to have resolved itself, if it comes up again I will check.
Not sure what changed.

**Comment by tzapu** [comment]
could you tell me if you were connecting to the esp from a mobile device or a computer/laptop?

**Comment by tablatronix** [comment]
IPHONE with serial monitor running on pc

**Comment by tzapu** [comment]
i ll close this. feel free to reopen it if you run into that again
thanks
