### ISSUE TITLE
Retry connection and json rest api

### ISSUE THREAD

**Issue by emrekilic** [tzapu/WiFiManager#252]
I will use this library in my project but i have questions before that.
1) When electricty cut off and on, my access point booting takes a long time but esp modules booting really fast. So esp can't connect to my access point and it starts in ap mode. Will it retry to connect my access point again because my access point will be avaliable after maybe 10 seconds. That would be perfect if it try to connect ap every 5 min even if in ap mode as chromecast. As i understand lib only tries to connect ap in setup one time.
2) Are there any version which consist rest api. I dont like html pages served with esp. Because its very limited. If any json rest api available, we can use it really easy with mobile native apps. And lib size will be smaller than that. If there is an option like that i will make android and ios apps and share them.

**Comment by kentaylor** [comment]
Autoconnect doesn't work well in the @emrekilic  scenario 1. The solution in [this version](https://github.com/kentaylor/WiFiManager) of WiFiManager is to [disable autoconnect](https://github.com/kentaylor/WiFiManager#configuration-portal-initiation-not-automatic) and rely on a button press but you'll be pleased to see that @tzapu is [already implementing](https://github.com/tzapu/WiFiManager/pull/157#issuecomment-260169950) your suggestion. It is interesting you mention Chromecast, I've tried out a few IOT commercial devices and Chromecast is the only one where I thought WiFi configuration worked well. Others I've tried work OK providing nothing goes wrong but have lots of confusing failure modes.

The @emrekilic  scenario 2 is satisfied [by this](https://github.com/kentaylor/WiFiManager#programmatic-configuration)  json interface and there is an [Android App](https://play.google.com/store/apps/details?id=au.com.umranium.espconnect) that uses it and provides a better user experience because it can swap between WiFi networks as required. You may have noticed that you can configure Chromecast only in an app or the Chrome browser. This is because the Chrome browser does allow control of the WiFi network, but this interface is only available to Google signed browser apps and not us.
