### ISSUE TITLE
HTML for Parameters

### ISSUE THREAD

**Issue by oscarmoutinho** [tzapu/WiFiManager#392]
'length' in 'WiFiManagerParameter' has 2 errors:
1- The <input> tag has a 'length' attribute and this should be 'maxlength' (see HTTP_FORM_PARAM[]).
2- The length seems to be trimmed to only one digit (I tested with 40 and the web page shows 4)

This does not generate wrong behaviour because 'length' is ignored, but 'length' should be applied correctly.

**Comment by Derek123456** [comment]
For 2) The culprit seems to be in WiFiManager.cpp line 488
`char parLength[2];`
This only leaves space for 1 character for the length and 1 null terminating character.

On line 500 the length value is copied into parLength
` snprintf(parLength, 2, "%d", _params[i]->getValueLength());`

If you increased size of parLength[] from 2 to 5 that would allow length values up to 9999 which should be more than enough.
