### ISSUE TITLE
Gives up too quickly

### ISSUE THREAD

**Issue by buzztiaan** [tzapu/WiFiManager#80]
Did i read right that it only tries connecting once, and then gives up and becomes an access point?

I think some configurable retry-count is in order, with some smallish delay between then. Just to make it a bit more userfriendly on not perfect reception locations :D

**Comment by tzapu** [comment]
hi, only tries once, 
but in my experience, when reception is poor, the connecting functions just stand there waiting a lot longer until they can establish the connection.
if you have those kinds of issues, maybe it s worth thinking about starting it on a button press rather than automatically... and on normal startup retry as you see fit

**Comment by buzztiaan** [comment]
whats the exact issue you are avoiding by not doing something as simple as 'try 5 times' ?

**Comment by tzapu** [comment]
needless delays, i am not a fan of delays :)
i ve got some battery powered sensors for instance, that could do without waiting for a number of retries 
(it could be set to 1, of course).
there are also some situations(routers i guess) in which i ve had the connection take a looong while before connecting, having 5 retries would mean it would take forever to get to see the configuration access point

**Comment by buzztiaan** [comment]
i see it give up within 3 seconds as-is, in situations where all wifi clients around it have a fine signal

i'll just fork and implement, see if it gets better
the default could be repeat once ;)

**Comment by tzapu** [comment]
for example, i have a router that at times takes 20 secs or more to connect or fail... i m saying 20 because i kind of give up counting by then, could be longer 30-40

**Comment by tzapu** [comment]
i ve also just thought of this, using the OnDemandConfigPortal + a WiFi.begin() in a loop of retries you can achieve exactly what you propose, so the tools are already there

**Comment by tzapu** [comment]
@buzztiaan i have added a new option to WiFiManger to set a connect timeout. 
in order to use this you d need to update to the latest github version of the lib and call 
`wifiManager.setConnectTimeout(30); `
before autoConnect. parameter is timeout in seconds . 
i am very intereste to know if this would help in your case

**Comment by buzztiaan** [comment]
I'll test it out within 24hrs!

**Comment by tzapu** [comment]
also, if that doesn t work, could you try the following sketch and see if you get a connection?
https://gist.github.com/tzapu/5b13866aaa584b32074a

**Comment by tablatronix** [comment]
It looks like the core autoconnect tries 3 times, but very quickly also.

**Comment by tzapu** [comment]
well, the thing is it gets the idle status set very fast, so it doesn t attempt anything else...

**Comment by tzapu** [comment]
hi, i ve just made another commit to this, could you please try the github version of WiFiManager and see if anything changed for you?

**Comment by buzztiaan** [comment]
been a while since i tried this

just grabbed latest version through libmanager, and all previous issues seem to not be present :D 
closing for now, will open new issue when it happens ;)
